export const EXERCISE_LIBRARY = [
    // Push
    { name: "Dips", category: "Push", equipment: "Bodyweight", bodyPart: "Triceps" },
    { name: "Push-ups", category: "Push", equipment: "Bodyweight", bodyPart: "Chest" },
    { name: "Dumbbell Bench Press", category: "Push", equipment: "Dumbbell", bodyPart: "Chest" },
    { name: "Dumbbell Incline Press", category: "Push", equipment: "Dumbbell", bodyPart: "Chest" },
    { name: "Dumbbell Overhead Press", category: "Push", equipment: "Dumbbell", bodyPart: "Shoulders" },
    { name: "Triceps Pushdowns", category: "Push", equipment: "Cable", bodyPart: "Triceps" },
    { name: "Close Grip Bench Press", category: "Push", equipment: "Barbell", bodyPart: "Triceps" },
    { name: "Incline Bench Press", category: "Push", equipment: "Barbell", bodyPart: "Chest" },
    { name: "Floor Press", category: "Push", equipment: "Barbell", bodyPart: "Triceps" },
    { name: "Spoto Press", category: "Push", equipment: "Barbell", bodyPart: "Chest" },
    { name: "Pin Press", category: "Push", equipment: "Barbell", bodyPart: "Triceps" },
    { name: "Push Press", category: "Push", equipment: "Barbell", bodyPart: "Shoulders" },
    { name: "Seated Overhead Press", category: "Push", equipment: "Barbell", bodyPart: "Shoulders" },
    { name: "Skullcrushers", category: "Push", equipment: "Barbell", bodyPart: "Triceps" },
    { name: "JM Press", category: "Push", equipment: "Barbell", bodyPart: "Triceps" },
    { name: "Landmine Press", category: "Push", equipment: "Barbell", bodyPart: "Shoulders" },

    // Pull
    { name: "Chin-ups", category: "Pull", equipment: "Bodyweight", bodyPart: "Back" },
    { name: "Pull-ups", category: "Pull", equipment: "Bodyweight", bodyPart: "Back" },
    { name: "Dumbbell Rows", category: "Pull", equipment: "Dumbbell", bodyPart: "Back" },
    { name: "Barbell Rows", category: "Pull", equipment: "Barbell", bodyPart: "Back" },
    { name: "Pendlay Rows", category: "Pull", equipment: "Barbell", bodyPart: "Back" },
    { name: "T-Bar Rows", category: "Pull", equipment: "Barbell", bodyPart: "Back" },
    { name: "Face Pulls", category: "Pull", equipment: "Cable", bodyPart: "Shoulders" },
    { name: "Lat Pulldowns", category: "Pull", equipment: "Machine", bodyPart: "Back" },
    { name: "Curls", category: "Pull", equipment: "Barbell", bodyPart: "Biceps" },
    { name: "Rack Pulls", category: "Pull", equipment: "Barbell", bodyPart: "Back" },
    { name: "Snatch Grip Deadlift", category: "Pull", equipment: "Barbell", bodyPart: "Back" },
    { name: "Romanian Deadlift", category: "Pull", equipment: "Barbell", bodyPart: "Legs" },
    { name: "Stiff Leg Deadlift", category: "Pull", equipment: "Barbell", bodyPart: "Legs" },
    { name: "Good Mornings", category: "Pull", equipment: "Barbell", bodyPart: "Back" },
    { name: "Power Clean", category: "Pull", equipment: "Barbell", bodyPart: "Full Body" },
    { name: "High Pulls", category: "Pull", equipment: "Barbell", bodyPart: "Back" },
    { name: "Shrugs", category: "Pull", equipment: "Barbell", bodyPart: "Back" },
    { name: "Preacher Curls", category: "Pull", equipment: "Barbell", bodyPart: "Biceps" },

    // Single Leg / Core
    { name: "Lunges", category: "Single Leg/Core", equipment: "Dumbbell", bodyPart: "Legs" },
    { name: "Barbell Lunges", category: "Single Leg/Core", equipment: "Barbell", bodyPart: "Legs" },
    { name: "Bulgarian Split Squats", category: "Single Leg/Core", equipment: "Dumbbell", bodyPart: "Legs" },
    { name: "Leg Press", category: "Single Leg/Core", equipment: "Machine", bodyPart: "Legs" },
    { name: "Hanging Leg Raises", category: "Single Leg/Core", equipment: "Bodyweight", bodyPart: "Abs" },
    { name: "Ab Wheel Rollouts", category: "Single Leg/Core", equipment: "Bodyweight", bodyPart: "Abs" },
    { name: "Planks", category: "Single Leg/Core", equipment: "Bodyweight", bodyPart: "Abs" },
    { name: "Back Extensions", category: "Single Leg/Core", equipment: "Machine", bodyPart: "Back" },
    { name: "Front Squat", category: "Single Leg/Core", equipment: "Barbell", bodyPart: "Legs" },
    { name: "Box Squat", category: "Single Leg/Core", equipment: "Barbell", bodyPart: "Legs" },
    { name: "Pause Squat", category: "Single Leg/Core", equipment: "Barbell", bodyPart: "Legs" },
    { name: "Zercher Squat", category: "Single Leg/Core", equipment: "Barbell", bodyPart: "Legs" },
    { name: "Split Squat", category: "Single Leg/Core", equipment: "Barbell", bodyPart: "Legs" },
    { name: "Step-ups", category: "Single Leg/Core", equipment: "Barbell", bodyPart: "Legs" },
    { name: "Hip Thrusts", category: "Single Leg/Core", equipment: "Barbell", bodyPart: "Legs" },
    { name: "Glute Bridge", category: "Single Leg/Core", equipment: "Barbell", bodyPart: "Legs" },
];
